### ISSUE TITLE
Mini code review of the latest changes

### ISSUE THREAD

**Issue by WestDiscGolf** [aarondcoleman/Fitbit.NET#100]
Apologies for the brain dump ...

* [Conditional("DEBUG")] statements in a library make my spidey sense tingle, but I guess code which is compiled out for release is good :-)

* The examples don't work anymore :-( Need this for RC. I think this is a downside of having multiple solution files loading in different project combinations. I think we might need to reassess this once oath 1 is removed as it can go back to a library project (as Common will have moved back into the fold), test project, console example and web example with one solution. For the nuget package generation we can have a different build configuration, thoughts?

* `public FitbitAppCredentials? AppCredentials { get; private set; }` is nullable, yet it's a property of a reference type so can be null, and it's only set in the constructor. I can't work out a reason why?

* Inconsistent usings locations in the files and formatting. `usings` should be outside of the namespace to be consistent with the majority of the code files.

* `DefaultTokenManager` I like this, concise, single responsibility. I'd put the HttpClient usage in a using though so there is less potential for a memory leak in the library.

* `RefreshAccessToken()` in Authenticator2 needs removing as it shouldn't be required any more and it's duplicated code. Would this potentially be a useful helper method? Not sure it's particularly discoverable at the moment though ...

* `FitbitAppCredentials` can't see why needed, why not pass in clientId and Secret into the constructor of FitbitClient? Keep it simple.

* IsTokenStale is duplicated ApiError parsing logic - this needs to be centralised.

* What is the thinking behind the constructor which takes `customFactory` to generate a httpclient? I think it's confusing and unsure what the use case is? 

* `ResponseHandler(Task<HttpResponseMessage> responseTask, CancellationToken cancellationToken)` Does it hyjack itself and almost recurse itself by using the HttpClient instance its part of to run again? So adding in a message handler and re-run internally? Or have I miss understood?

* `FitbitHttpClientMessageHandler` - "Fitbit.Net-StaleTokenRetry" should be a constant at minimum. Consistent none standard headers usually have the prefix "X-" eg "X-Fitbit-Subscriber-Id". So we could add in "X-Fitbit.NET-StaleTokenRetry"?

* `FitbitHttpClientMessageHandler` - needs general tidying; no need for `this` references etc. Debug.WriteLine I don't think should be part of a library unless there is an interface where someone can inject a logger interface we can hook in to. The debugging and logging the response/request functionality should be done by an interceptor which can be loaded if required when being instantiated by the consumer of the library.

* `OAuth2Helper` need to remove unrequired consts and move the others to constants.cs - consistency.

* The Constants.Cs file needs updating / cleaning. Generally the url structure creation routines need cleaning up as they don't seem to be moving as often as originally thought they could be put into a single place - removing all the oauth 1 related url parts.

* `OAuth2Helper` the url doesn't change, the stringbuilder is a bit overkill I think.

* 'OAuth2Helper` ParseAccessTokenResponse needs updating - Fitbit exception being thrown - new FitbitException for parsing issues for responses we should be able to handle?

* `OAuth2Helper` the parsing for the token could be done with attributes on the properties through Json.net. Thoughts?

* 'OAuth2AccessToken` inconsistent formatting (whitespace)

I think the message handler which has been added to handle the stale tokens and retries etc. is a good idea but I think it's trying to be a jack of all trades and in doing so has made it quite tricky to understand. We don't need to be limited to one, it is a pipeline after all, which we can plug in to. We could have a specific "stale token retry" message handler which is the outer most handler (or first in the pipeline so executed first (request) and last (response)) which handles authorisation, stale tokens, refresh tokens etc. and then have another logger one etc. but also allow people to write others as per my pipeline branch.

I completely understand a lot of the development is being driven by the need of Fitabase but personally it feels a bit application like code at the moment (which I understand why) but I feel it needs to be a bit tighter and more what I feel should be library like so it can be used for a number of use cases.

Happy to discuss further and would appreciate feedback / comments on the above.

**Comment by mxa0079** [comment]
I'm glad it was only a "mini" code review ;)
In all seriousness, thanks for the feedback. See inline replies here:

- [Conditional("DEBUG")] statements in a library make my spidey sense tingle, but I guess code which is compiled out for release is good :-) 
  - Yes, not a huge fan either but this will never make it to an official package. I needed it to make the debug logging work while keeping the tests simple.
-The examples don't work anymore :-( Need this for RC. I think this is a downside of having multiple solution files loading in different project combinations. I think we might need to reassess this once oath 1 is removed as it can go back to a library project (as Common will have moved back into the fold), test project, console example and web example with one solution. For the nuget package generation we can have a different build configuration, thoughts?
  -Updated OAuth2 sample in PR #104 so it will work with late changes. 
  -However, samples should not be part of the main solution, it affects build automation time, and adds unnecessary overhead to main solution (why open and build a full blown mvc site when working on a class library). We can keep multiple solutions, and ensure they stay up to date with package. In the future we can even remove the  direct project references to the sample solutions and point them to the beta feed of the nuget package.
- `public FitbitAppCredentials? AppCredentials { get; private set; }` is nullable, yet it's a property of a reference type so can be null, and it's only set in the constructor. I can't work out a reason why?
  - FitbitAppCredentials was a struct, hence it could not be null. However, there is no need to turn this into a struct since it is so seldomly used. It now is a class in PR #105
- Inconsistent usings locations in the files and formatting. usings should be outside of the namespace to be consistent with the majority of the code files.
  - I'll address this on an upcoming style PR
- DefaultTokenManager I like this, concise, single responsibility. I'd put the HttpClient usage in a using though so there is less potential for a memory leak in the library.
  - HttpClient is actually meant to be long lived. The using directive with HttpClient can cause memory leaks. More info: [here] (http://stackoverflow.com/questions/15705092/do-httpclient-and-httpclienthandler-have-to-be-disposed) and [here] (http://stackoverflow.com/questions/27732546/httpclienthandler-httpclient-memory-leak)
- RefreshAccessToken() in Authenticator2 needs removing as it shouldn't be required any more and it's duplicated code. Would this potentially be a useful helper method? Not sure it's particularly discoverable at the moment though …
  - See PR #109
- FitbitAppCredentials can't see why needed, why not pass in clientId and Secret into the constructor of FitbitClient? Keep it simple.
  - Using data objects like this one helps readability. 
- IsTokenStale is duplicated ApiError parsing logic - this needs to be centralised.
 - See Issue #108 
- What is the thinking behind the constructor which takes customFactory to generate a httpclient? I think it's confusing and unsure what the use case is? 
  - This was the central subject of a fun discussion I had with aaron the other day. Here is a summary:
    - There are many HttpClient properties that can only be set when the instance is created. In case we need access to change this properties in the future (we don't know what we don’t know), we wanted a way to provide our own "HttpClient Factory". We considered the following options:
      - Adding a constructor that takes HttpClient as an argument
        - **Pros:** Simple
        - **Cons:** May be misleading to newcomers of the library, it is incompatible with IFitbitInterceptor
      - Adding a constructor that takes a newly introduced IHttpClient interface with a Create method that returns an HttpClient as in `new FitbitClient(HttpClient IHttpClient.Create());
          - **Pros:** Gets the job done. Keeps new developers away from advanced functionality. Compatible with IFitbitInterceptor
        - **Cons:** Too much ceremony. Higher entry cost (which I see as a plus, as we want to keep this for edge cases)
      - Adding an inline interface (a.k.a a Func<> argument)
        - **Pros:** Low ceremony. Reusable. Keeps new developers away from advanced functionality. Low ceremony. Compatible with IFitbitInterceptor. Keeps codebase cleaner
        - **Cons:** Requires understanding of Func and lambda expressions in C#. Higher entry cost (which I see as a plus, as we want to keep this for edge cases)
-  `ResponseHandler(Task<HttpResponseMessage> responseTask, CancellationToken cancellationToken)` Does it hyjack itself and almost recurse itself by using the `HttpClient` instance its part of to run again? So adding in a message handler and re-run internally? Or have I miss understood?
  - `FitbitHttpClientMessageHandler`, through `ResponseHandler`, does two things  when FitbitClient receives an `HttpResponseMessage` : 
      - It checks if access is denied due to a stale token, and kicks of the token refresh process (whose behavior can be injected through ITokenManager)
      - It wires IFitbitInterceptor
- 	FitbitHttpClientMessageHandler - "Fitbit.Net-StaleTokenRetry" should be a constant at minimum. Consistent none standard headers usually have the prefix "X-" eg "X-Fitbit-Subscriber-Id". So we could add in "X-Fitbit.NET-StaleTokenRetry"?
    - See PR #110
- FitbitHttpClientMessageHandler - needs general tidying; no need for this references etc. Debug.WriteLine I don't think should be part of a library unless there is an interface where someone can inject a logger interface we can hook in to. The debugging and logging the response/request functionality should be done by an interceptor which can be loaded if required when being instantiated by the consumer of the library.
    - `FitbitHttpClientMessageHandler` responsibility should be to wire the pipeline into `IFitbitInterceptor`. I agree that we need to remove some of its current responsibilities. I have an upcoming PR to address this.
- OAuth2Helper need to remove unrequired consts and move the others to constants.cs - consistency.
    - Issue #107
- The Constants.Cs file needs updating / cleaning. Generally the url structure creation routines need cleaning up as they don't seem to be moving as often as originally thought they could be put into a single place - removing all the oauth 1 related url parts.
    - Issue #107
- OAuth2Helper the url doesn't change, the stringbuilder is a bit overkill I think.
    - Feel free to change it
- 'OAuth2Helper` ParseAccessTokenResponse needs updating - Fitbit exception being thrown - new FitbitException for parsing issues for responses we should be able to handle?  
    - Issue #106
- OAuth2Helper the parsing for the token could be done with attributes on the properties through Json.net. Thoughts?
    - Feel free to work on this
- 'OAuth2AccessToken` inconsistent formatting (whitespace)
    - I do not see the inconsistency, please be more sp

**Comment by WestDiscGolf** [comment]
I've read the comments and will respond in more detail later.

Thanks for the links to `HttpClient` usage - every day is a school day! :-)

**Comment by WestDiscGolf** [comment]
Looks good. Like how each point has been split into separate issue to be resolved :-)

**Comment by WestDiscGolf** [comment]
Re: HttpClient, interesting read - http://chimera.labs.oreilly.com/books/1234000001708/ch14.html

**Comment by mxa0079** [comment]
Ping to @aarondcoleman to checkout the link that @WestDiscGolf shared.

**Comment by mxa0079** [comment]
And closing the issue since feedback has either been addressed or logged as a separate issue.
