### ISSUE TITLE
OAuth 2.0 Desktop support

### ISSUE THREAD

**Issue by ReevMich** [aarondcoleman/Fitbit.NET#158]
Im trying to figure out how, i would try to implement a basic desktop application to work with the Portable Library.

Any suggestions?

**Comment by mxa0079** [comment]
For a desktop application you would need to use the implicit grant flow, which is not yet implemented in the library. See issue #89 for details. 

Our focus on the library has been for server side scenarios, but we would like to include support for this in the future. Feel free to take a stab at it and send a PR ;) 

Since this is already being tracked by #89 I will close this issue, we can continue the conversation in there.
