### ISSUE TITLE
FitbitClient.cs file is becoming large

### ISSUE THREAD

**Issue by aarondcoleman** [aarondcoleman/Fitbit.NET#52]
Carrying this over from @WestDiscGolf previous comment here: https://github.com/aarondcoleman/Fitbit.NET/issues/46#issuecomment-160224502

>I've been thinking about the library as a whole with everything we've discussed over the past 6-12 months and looking/using other libraries recently it's allowed me to see how others have approached a similar issue and addressed it. I also had an issue with how big the "FitbitClient" class was getting as it was getting too unweilding. So taking all this into account I've had a bit of a play and finally got around to publishing the results. It's a bit raw and the tests project doesn't build but the methods I've implemented (GetDevices, Get friends) work - https://github.com/WestDiscGolf/Fitbit.NET/tree/async-portable-update

>It's only a potential idea, so wanted to put it out there before going too far. Let me know what you think.

>Cheers

I took a look and it seems like you're proposing we create, sort of a mini-client per category of the API client class? Like, DevicesClient and FriendsClient? Hmm, I'm not sure that's any more clearer. What about keeping the FitbitClient class intact and using partial classes such that we can group resource collection calls together? Like:
* FitbitClient.Friends.cs
* FitbitClient.Devices.cs
* FitbitClient.Weight.cs
* FitbitClient.Heartrate.cs
* ...etc
?

**Comment by WestDiscGolf** [comment]
Personally I think breaking it into partial classes won't resolve the issue either. I think for a class, of the size it currently is won't benefit from partialisation (just made that up! I think?!). Breaking up the functionality and leaving the FitbitClient as the facade into the library makes it clearer. This way you can keep the public facing API the same and keep the related functionality together in different classes. This will make testing easier etc.

Although to be honest, at the end of the day, it's how we want the code base to look to make it easier for us to make changes and accept contributions because the external facing API (as previously said) once you compile and/or download the nuget package will be the same.

**Comment by WestDiscGolf** [comment]
After discussion as long as we keep the file tidy then it will be ok for now. We can re-assess in the future as we add more functionality. We can probable close this now.

**Comment by WestDiscGolf** [comment]
Ping - lets close this :-)

**Comment by mxa0079** [comment]
I'd like to revisit this after we release V2... Closing for now.
