### ISSUE TITLE
Which  branch for oauth2?

### ISSUE THREAD

**Issue by victw** [aarondcoleman/Fitbit.NET#59]
Newbie here.  Not native to c# and also stumbling on git.  But if I can get these going I would love to participate.
Here's the thing - I just signed up to the fitbit apis.  I can get the master branch to build and execute.  

However my understanding is that I need to get up to speed on oauth2.  

When I switch to branch async-portable-oauth2-tokenstore I can't get a clean build.

Can anyone point this newbie in the right direction.  
Am I on the right branch for oauth2?
Is it likely an environment issue?  Do I just need to slog through the error messages.

Thanks for all your help.
Vic

**Comment by eveko** [comment]
I am currently playing around with the async-portable. Authorization works but loading data from the model seems problematic

**Comment by aarondcoleman** [comment]
Hi @victw @eveko Newbies welcome!

Yes, async-portable but we'll soon take existing master, spin it off as a branch, and promote async-portable as master. There are a few core issues we're tackling which may have some breaking changes there in the next week or two those should be done. Keep an eye on the issues tab and if you find some specific ones don't hesitate to add an issue so we can figure out what's going on and tackle it. Since this is more a generic question, happy to answer it here but I'm closing it so we can keep the unsolved issue list current.
